### ISSUE TITLE
-1 not enough babel

### ISSUE THREAD

**Issue by vihanb** [molarmanful/edon#1]
you should use babel. Normal ES5 is ugly, yuck

**Comment by molarmanful** [comment]
https://imgflip.com/i/13xljp

**Comment by vihanb** [comment]
this is not a bug which is "fixed" this is a critical issue which is "solved", so you cannot use that meme

**Comment by molarmanful** [comment]
dangit

**Comment by molarmanful** [comment]
<img src="https://i.imgflip.com/13xlp2.jpg">

**Comment by molarmanful** [comment]
Ok I've added Babel as a backup.

**Comment by vihanb** [comment]
:D :D :D  :D :D :D :D :D :D :D :D :D :D :D :D
